# Generated by Django 5.2.4 on 2025-07-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('release_year', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('rating', models.FloatField()),
                ('poster_url', models.URLField()),
                ('backdrop_url', models.URLField()),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('is_4k', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('genres', models.ManyToManyField(to='movies.genre')),
            ],
        ),
    ]
