# Generated by Django 5.2.4 on 2025-07-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster_url',
            field=models.ImageField(upload_to=''),
        ),
    ]
