# Generated by Django 5.2.4 on 2025-07-06 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_poster_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='is_4k',
            new_name='is4k',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='is_new',
            new_name='isNew',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='poster_url',
            new_name='poster',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='rating',
            new_name='rate',
        ),
    ]
