# Generated by Django 5.2.4 on 2025-07-06 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_rename_is_4k_movie_is4k_rename_is_new_movie_isnew_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='release_year',
            new_name='year',
        ),
    ]
