# Generated by Django 5.2.4 on 2025-07-06 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_remove_movie_logo_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='is4k',
            new_name='is_4k',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='isNew',
            new_name='is_new',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='poster',
            new_name='poster_url',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='rate',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='year',
            new_name='release_year',
        ),
    ]
