# Generated by Django 5.2.4 on 2025-07-07 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_rename_is4k_movie_is_4k_rename_isnew_movie_is_new_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='movie',
            name='download_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in minutes', null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.CharField(blank=True, help_text='YouTube video ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_year',
            field=models.PositiveIntegerField(),
        ),
    ]
