# Generated by Django 5.2.4 on 2025-07-07 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_tvshow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TVShow',
        ),
    ]
