# Generated by Django 5.2.4 on 2025-07-08 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_tvshow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TVShow',
        ),
    ]
