# Generated by Django 5.2.4 on 2025-07-08 15:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0015_delete_tvshow'),
    ]

    operations = [
        migrations.CreateModel(
            name='TVShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('release_year', models.PositiveIntegerField()),
                ('rating', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('poster_image', models.ImageField(blank=True, null=True, upload_to='tv_posters/')),
                ('backdrop_image', models.ImageField(blank=True, null=True, upload_to='tv_backdrops/')),
                ('poster_url', models.URLField(blank=True, null=True)),
                ('backdrop_url', models.URLField(blank=True, null=True)),
                ('trailer_url', models.CharField(blank=True, max_length=512, null=True)),
                ('seasons', models.PositiveIntegerField(default=1)),
                ('episodes', models.PositiveIntegerField(default=1)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('is_featured', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('is_trending', models.BooleanField(default=False)),
                ('director', models.CharField(blank=True, max_length=255, null=True)),
                ('cast', models.TextField(blank=True, help_text='Comma separated list of actors', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genres', models.ManyToManyField(to='movies.genre')),
            ],
            options={
                'verbose_name': 'TV Show',
                'verbose_name_plural': 'TV Shows',
                'ordering': ['-created_at'],
            },
        ),
    ]
