# Generated by Django 5.2.4 on 2025-07-09 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_tvshow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('overview', models.TextField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Duration in minutes', null=True)),
                ('air_date', models.DateField(blank=True, null=True)),
                ('still_image', models.ImageField(blank=True, null=True, upload_to='episode_stills/')),
                ('still_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['episode_number'],
            },
        ),
        migrations.RemoveField(
            model_name='tvshow',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='tvshow',
            name='episodes',
        ),
        migrations.CreateModel(
            name='EpisodeDownloadLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(choices=[('SD', 'Standard Definition'), ('HD', 'High Definition'), ('4K', 'Ultra HD')], max_length=10)),
                ('url', models.URLField()),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_links', to='movies.episode')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('poster_image', models.ImageField(blank=True, null=True, upload_to='season_posters/')),
                ('poster_url', models.URLField(blank=True, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('tv_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tv_seasons', to='movies.tvshow')),
            ],
            options={
                'ordering': ['season_number'],
                'unique_together': {('tv_show', 'season_number')},
            },
        ),
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='movies.season'),
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('season', 'episode_number')},
        ),
    ]
