# Generated by Django 5.2.4 on 2025-07-09 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_episode_remove_tvshow_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episodedownloadlink',
            name='episode',
        ),
        migrations.AlterModelOptions(
            name='tvshow',
            options={},
        ),
        migrations.RemoveField(
            model_name='season',
            name='overview',
        ),
        migrations.RemoveField(
            model_name='season',
            name='poster_image',
        ),
        migrations.RemoveField(
            model_name='season',
            name='poster_url',
        ),
        migrations.RemoveField(
            model_name='season',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='season',
            name='title',
        ),
        migrations.RemoveField(
            model_name='tvshow',
            name='seasons',
        ),
        migrations.AddField(
            model_name='season',
            name='download_links',
            field=models.JSONField(default=dict, help_text="Format: {'1': {'HD': 'url1', '4K': 'url2'}, '2': {...}}"),
        ),
        migrations.AddField(
            model_name='season',
            name='episode_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='season',
            name='tv_show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='movies.tvshow'),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='cast',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Episode',
        ),
        migrations.DeleteModel(
            name='EpisodeDownloadLink',
        ),
    ]
