# Generated by Django 5.2.4 on 2025-07-09 00:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0018_remove_episodedownloadlink_episode_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['season_number'], 'verbose_name': 'Season', 'verbose_name_plural': 'Seasons'},
        ),
        migrations.AlterField(
            model_name='season',
            name='download_links',
            field=models.JSONField(blank=True, default=dict, help_text="Format: {'1': {'HD': 'url1', '4K': 'url2'}, '2': {...}}"),
        ),
        migrations.AlterField(
            model_name='season',
            name='episode_count',
            field=models.PositiveIntegerField(default=1, help_text='Total number of episodes in this season', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='season',
            name='season_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
