# Generated by Django 5.2.4 on 2025-07-09 00:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0019_alter_season_options_alter_season_download_links_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['season_number']},
        ),
        migrations.RemoveField(
            model_name='season',
            name='download_links',
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='movies.season')),
            ],
            options={
                'ordering': ['episode_number'],
                'unique_together': {('season', 'episode_number')},
            },
        ),
        migrations.CreateModel(
            name='DownloadLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(choices=[('HD', 'High Definition'), ('4K', 'Ultra HD'), ('SD', 'Standard Definition')], max_length=10)),
                ('url', models.URLField()),
                ('source', models.CharField(blank=True, help_text='Optional: Source of this download', max_length=100, null=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_links', to='movies.episode')),
            ],
            options={
                'unique_together': {('episode', 'quality')},
            },
        ),
    ]
