# Generated by Django 5.2.4 on 2025-07-09 12:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0020_alter_season_options_remove_season_download_links_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BongoMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('release_year', models.PositiveIntegerField()),
                ('rating', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('poster_image', models.ImageField(blank=True, null=True, upload_to='bongomovie_posters/')),
                ('poster_url', models.URLField(blank=True, null=True)),
                ('backdrop_image', models.ImageField(blank=True, null=True, upload_to='bongomovie_backdrops/')),
                ('backdrop_url', models.URLField(blank=True, null=True)),
                ('trailer_url', models.CharField(blank=True, help_text='YouTube video ID', max_length=100, null=True)),
                ('download_url', models.URLField(blank=True, null=True)),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Duration in minutes', null=True)),
                ('director', models.CharField(blank=True, max_length=200)),
                ('cast', models.TextField(blank=True)),
                ('is_4k', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genres', models.ManyToManyField(to='movies.genre')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
