# Generated by Django 5.2.4 on 2025-07-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0021_bongomovie'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('stream_url', models.URLField(help_text='URL for live stream (e.g., HLS, YouTube Live)')),
                ('poster_image', models.ImageField(blank=True, null=True, upload_to='livestream_posters/')),
                ('poster_url', models.URLField(blank=True, null=True)),
                ('backdrop_image', models.ImageField(blank=True, null=True, upload_to='livestream_backdrops/')),
                ('backdrop_url', models.URLField(blank=True, null=True)),
                ('is_live', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genres', models.ManyToManyField(to='movies.genre')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
