# Generated by Django 5.2.4 on 2025-07-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0022_livestream'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livestream',
            name='stream_url',
        ),
        migrations.AddField(
            model_name='livestream',
            name='video_file',
            field=models.FileField(default='', help_text='Upload video file for live streaming (e.g., MP4, WebM)', upload_to='livestream_videos/'),
        ),
    ]
